# Generated by Django 4.2.14 on 2024-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='list_id',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
