# Generated by Django 4.2.14 on 2024-08-10 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0003_remove_todo_list_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='list_id',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
