# Generated by Django 4.2.14 on 2024-08-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_todo_list_list_id_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_on']},
        ),
    ]
