# Generated by Django 4.2.14 on 2024-08-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='author',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='todo_list',
        ),
    ]
