# Generated by Django 4.2.14 on 2024-08-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_list',
            old_name='author',
            new_name='user',
        ),
    ]
