# Generated by Django 4.2.14 on 2024-08-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_rename_author_todo_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_list.todo_list'),
        ),
    ]
