# Generated by Django 4.2.14 on 2024-08-07 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0012_task_todo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='content',
        ),
        migrations.RemoveField(
            model_name='todo_list',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='todo_list',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
