# Generated by Django 4.2.14 on 2024-08-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_remove_todo_list_content_remove_todo_list_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='slug',
        ),
    ]
